### ISSUE TITLE
How to create admin, how to signup user?

### ISSUE THREAD

**Issue by younthu** [codealchemy/BookLibrary#23]
Hi,

This is a great project, we want to use it for our internal use.

Can you tell me how can i create an admin user?
How can user signup with email?

Thanks.

**Comment by younthu** [comment]
Sorry to bother you!

Fixed via console

`
u = User.create(:email => "kingla_pei@163.com", :password => '11111111', :password_confirmation => '11111111', :admin => true)
`

**Comment by codealchemy** [comment]
@younthu no problem (and glad you were able to resolve it)! That was exactly what I was going to suggest - another way would be to update the [`user_registrations#new`](https://github.com/codealchemy/BookLibrary/blob/master/app/views/devise/registrations/new.html.erb) partial to allow people to sign up (the original signup form can be found [here](https://github.com/codealchemy/BookLibrary/blob/09fb92f94765fb3675815523ea3ab942682a1cdf/app/views/devise/registrations/new.html.erb))

**Comment by younthu** [comment]
Thank you @codealchemy ! 

I've forked your repository and will try to host it for internal use, If there is any license issue, please let me know.

Thanks for your great contribution!
